name: Regression Tests

on: [push, pull_request]

jobs:
  build:
    name: Python (${{ matrix.group }}/10)
    runs-on: ubuntu-24.04
    
    strategy:
      matrix:
        group: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

    steps:
    - uses: actions/checkout@v3

    - name: Install Ubuntu packages
      run: |
        sudo apt install -y --no-install-recommends iverilog verilator

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions

    - name: Test with tox
      run: tox -- -n auto --verbose --splits 10 --group ${{ matrix.group }} --splitting-algorithm least_duration
